### ISSUE TITLE
run_GB_family

### ISSUE THREAD

**Issue by arizeo** [scarpino/binequality#1]
I am trying to run the example for run_GB_family:

data(state_bins)

use_states <- which(state_bins[,'State'] == 'Texas')
TX <- state_bins[use_states,]

LNO_WEI_GA <- run_GB_family(ID = TX[,'State'], hb = TX[,'hb'], 
bin_min = TX[,'bin_min'], bin_max = TX[,'bin_max'], obs_mean = 
rep(NA, length(use_states)), ID_name = "State", quantiles = 
seq(0.006,0.996, length.out = 1000), modelsToFit = 
c('LNO','WEI','GA'))

I have checked on several machines to see if it wasn't coming from the fact that I am using Linux. I also checked that the data was loaded but the output is not right:

> LNO_WEI_GA
$fit
  State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic didConverge logLikelihood nparams median sd G2 df  p
1 Texas      NA          LNO      NA  NA NA     NA   NA    NA  NA  NA  NA       FALSE            NA      NA     NA NA NA NA NA
2 Texas      NA          WEI      NA  NA NA     NA   NA    NA  NA  NA  NA       FALSE            NA      NA     NA NA NA NA NA
3 Texas      NA           GA      NA  NA NA     NA   NA    NA  NA  NA  NA       FALSE            NA      NA     NA NA NA NA NA

$fit.filter
  State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic didConverge logLikelihood nparams median sd waicCon waicNoCon wbicCon
1 Texas      NA          LNO      NA  NA NA     NA   NA    NA  NA  NA  NA       FALSE            NA      NA     NA NA      NA        NA      NA
2 Texas      NA          WEI      NA  NA NA     NA   NA    NA  NA  NA  NA       FALSE            NA      NA     NA NA      NA        NA      NA
3 Texas      NA           GA      NA  NA NA     NA   NA    NA  NA  NA  NA       FALSE            NA      NA     NA NA      NA        NA      NA
  wbicNoCon G2 df  p
1        NA NA NA NA
2        NA NA NA NA
3        NA NA NA NA

$best_model
$best_model$aic
  State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic didConverge logLikelihood nparams median sd
1 Texas      NA           NA      NA  NA NA     NA   NA    NA  NA  NA  NA          NA            NA      NA     NA NA

$best_model$bic
  State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic didConverge logLikelihood nparams median sd
1 Texas      NA           NA      NA  NA NA     NA   NA    NA  NA  NA  NA          NA            NA      NA     NA NA

$best_model$aicAvg
[1] "nothingConverged"

$best_model$bicAvg
[1] "nothingConverged"

$best_model$waic
[1] NA NA NA

$best_model$wbic
[1] NA NA NA

$best_model.filter
$best_model.filter$aic
  State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic didConverge logLikelihood nparams median sd
1 Texas      NA           NA      NA  NA NA     NA   NA    NA  NA  NA  NA          NA            NA      NA     NA NA

$best_model.filter$bic
  State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic didConverge logLikelihood nparams median sd
1 Texas      NA           NA      NA  NA NA     NA   NA    NA  NA  NA  NA          NA            NA      NA     NA NA

$best_model.filter$aicAvg
[1] "nothingConverged"

$best_model.filter$bicAvg
[1] "nothingConverged"

$best_model.filter$waic
[1] NA NA NA

$best_model.filter$wbic
[1] NA NA NA

**Comment by scarpino** [comment]
Thanks for the note.  The gamlss package was recently updated and some of
the function names changed.  I’m trying to find time to push an update, but
am slammed with teaching right now.  In the meantime, the below code should
solve the problem. Thanks for your interest in our work and again for point
out the bug.

Sam

library(binequality)

data(state_bins)

use_states <- which(state_bins[,'State'] == 'Texas' | state_bins[,'State']
== 'California')

log_normal_fit <- fitFunc(ID = state_bins[use_states,'State'], hb =
state_bins[use_states,'hb'], bin_min = state_bins[use_states,'bin_min'],
bin_max = state_bins[use_states,'bin_max'], obs_mean = rep(NA,
length(use_states)), ID_name = 'State',  distribution = "LOGNO", distName =
"LNO", links = c(muLink = identity, sigmaLink = log, nuLink = NULL, tauLink
= NULL), qFunc = qLOGNO, quantiles = seq(0.006, 0.996, length.out = 100),
linksq = c(identity, exp, NULL, NULL), con =
gamlss.control(c.crit=0.1,n.cyc=200, trace=FALSE), saveQuants = FALSE,
muStart = NULL, sigmaStart = NULL, nuStart = NULL, tauStart = NULL, muFix =
FALSE, sigmaFix = FALSE, nuFix = FALSE, tauFix = FALSE, freeParams =
c(TRUE, TRUE, FALSE, FALSE), smartStart = FALSE, tstamp =
as.numeric(Sys.time()))


On December 10, 2016 at 6:43:24 PM, ValoData (notifications@github.com)
wrote:

I am trying to run the example for run_GB_family:

data(state_bins)

use_states <- which(state_bins[,'State'] == 'Texas')
TX <- state_bins[use_states,]

LNO_WEI_GA <- run_GB_family(ID = TX[,'State'], hb = TX[,'hb'],
bin_min = TX[,'bin_min'], bin_max = TX[,'bin_max'], obs_mean =
rep(NA, length(use_states)), ID_name = "State", quantiles =
seq(0.006,0.996, length.out = 1000), modelsToFit =
c('LNO','WEI','GA'))

I have checked on several machines to see if it wasn't coming from the fact
that I am using Linux. I also checked that the data was loaded but the
output is not right:

LNO_WEI_GA
$fit
State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic
didConverge logLikelihood nparams median sd G2 df p
1 Texas NA LNO NA NA NA NA NA NA NA NA NA FALSE NA NA NA NA NA NA NA
2 Texas NA WEI NA NA NA NA NA NA NA NA NA FALSE NA NA NA NA NA NA NA
3 Texas NA GA NA NA NA NA NA NA NA NA NA FALSE NA NA NA NA NA NA NA

$fit.filter
State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic
didConverge logLikelihood nparams median sd waicCon waicNoCon wbicCon
1 Texas NA LNO NA NA NA NA NA NA NA NA NA FALSE NA NA NA NA NA NA NA
2 Texas NA WEI NA NA NA NA NA NA NA NA NA FALSE NA NA NA NA NA NA NA
3 Texas NA GA NA NA NA NA NA NA NA NA NA FALSE NA NA NA NA NA NA NA
wbicNoCon G2 df p
1 NA NA NA NA
2 NA NA NA NA
3 NA NA NA NA

$best_model
$best_model$aic
State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic
didConverge logLikelihood nparams median sd
1 Texas NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

$best_model$bic
State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic
didConverge logLikelihood nparams median sd
1 Texas NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

$best_model$aicAvg
[1] "nothingConverged"

$best_model$bicAvg
[1] "nothingConverged"

$best_model$waic
[1] NA NA NA

$best_model$wbic
[1] NA NA NA

$best_model.filter
$best_model.filter$aic
State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic
didConverge logLikelihood nparams median sd
1 Texas NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

$best_model.filter$bic
State obsMean distribution estMean var cv cv_sqr gini theil MLD aic bic
didConverge logLikelihood nparams median sd
1 Texas NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

$best_model.filter$aicAvg
[1] "nothingConverged"

$best_model.filter$bicAvg
[1] "nothingConverged"

$best_model.filter$waic
[1] NA NA NA

$best_model.filter$wbic
[1] NA NA NA

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scarpino/binequality/issues/1>, or mute the thread

**Comment by scarpino** [comment]
This issue is resolved with v1.02
